### PR TITLE
first change to start

### PR DESCRIPTION
**Pull request by Amin-Hashemian2021**

### CODE REVIEW

**Comment by Amin-Hashemian2021** [comment]
in last home page update i change home pill nav link design and solved the responsive problems of pill nav.

**Comment by iamamonte** [comment]
I think there is some confusion around merging and pull requests. This link may help:

https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/proposing-changes-to-your-work-with-pull-requests

Feel free to reach out via email for clarification.

**Comment by Amin-Hashemian2021** [comment]
Thank you sir I will try to solve the problems in a few hours.

iamamonte ***@***.***>, 14 Mar 2021 Paz, 19:00 tarihinde şunu
yazdı:

**Comment by Amin-Hashemian2021** [comment]
..

**Comment by Amin-Hashemian2021** [comment]
I made changes in the code, but I am encountering such an error in pull
request, what I think is something related to the version of node js.
today i can't do this but i can solve it in a few days

Amin Hashemian ***@***.***>, 15 Mar 2021 Pzt, 15:37
tarihinde şunu yazdı:

**Comment by Amin-Hashemian2021** [comment]
pro.zip
<https://drive.google.com/file/d/1APTDg5rX9kVhXdMR3CVxIV5YiZIL2S6T/view?usp=drive_web>
There are changes in my git hub account
in the file I sent for all changes today

Amin Hashemian ***@***.***>, 15 Mar 2021 Pzt, 19:40
tarihinde şunu yazdı:

**Pull request closed without merging**
